from setuptools import setup, find_packages


setup(
    name='pavlok',
    version='0.1.0',
    license='MIT',
    author="Maneesh Sethi",
    author_email='maneesh@pavlok.com',
    packages=find_packages('src'),
    package_dir={'': 'src'},
    url='https://github.com/Pavlok/pavlok-python-client',
    keywords='pavlok',
    install_requires=[
        'anyio==3.3.1',
        'asgiref==3.4.1',
        'Authlib==1.0.0b1',
        'certifi==2021.5.30',
        'cffi==1.14.6',
        'charset-normalizer==2.0.5',
        'click==8.0.1',
        'cryptography==3.4.8',
        'fastapi==0.68.1',
        'Flask==2.0.1',
        'h11==0.12.0',
        'httpcore==0.13.7',
        'httpx==0.19.0',
        'idna==3.2',
        'itsdangerous==2.0.1',
        'Jinja2==3.0.1',
        'MarkupSafe==2.0.1',
        'pycparser==2.20',
        'pydantic==1.8.2',
        'python-dotenv==0.19.0',
        'requests==2.26.0',
        'rfc3986',
        'sniffio==1.2.0',
        'starlette',
        'typing-extensions==3.10.0.2',
        'urllib3==1.26.6',
        'uvicorn==0.15.0',
        'Werkzeug==2.0.1',
      ],

)